# Generated by Django 5.0.1 on 2024-01-27 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Equipe',
            new_name='Funcionario',
        ),
    ]
