# Generated by Django 5.0.1 on 2024-01-28 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recursos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recursos',
        ),
    ]
